version: '3.8'
services:
  mysql-inventory:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin123admin
      MYSQL_DATABASE: InventService
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql-inventory:
        condition: service_healthy